language : java

jdk:
  - oraclejdk8

dist: trusty

addons:
  sonarcloud:
    organization: "asyard-github" # the key of the org you chose at step #3

script:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn clean verify
 - mvn clean install
 - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN}

after_success:
  - bash <(curl -s https://codecov.io/bash)