language : java

addons:
  sonarcloud:
    organization: "Asy"
    token:
      secure: "AFcwdiyZTv/D/8P9HZEZLoQQ9DXssyEkGXR2JqZdiWCz+BnlvgeljBGXuaj8O77a7lDd3w9otr3Se+BdXwF1C+LNqXoGdg6J/2ctDn8d2NNQBNTmhW0DhE7NlxOLyUpCQ0qKmChQ+JQ9oVGXvhZ4tF6mAKz8JOjbg8EPypBuiFsHgxvulLcUmrJDC/Vu9osoExlCXADvgyUJH4RZD0JFExSyIr0a1onVkFTCWz9DlGBoCAuO2X380XAQJuWbiEM4uezkaWdMMbNqtL3L8tMKkj+puISwv3/3ftYq8fPdUXt0DLv0D/WZnNTgP4uYkqaMAqLKViOvWoEdQFv0P9YVRFC0Gd3POGX7frhj54VnPBM19PLnLg8NxBUzx5Mch+fEr6ukmTOGlrSjjNj3JDpQTn9l0uvMpTy62iK16oxJFJ6NLCYWS6McGiYJOp6j+yrX0TkpGfqOaaDR4jFgOVztGqxMhL5UA/SILa6hT0BOfpmagBYwRITt3b7gs8NBm9zWRppToqaDxb3Yplmy1O8V+ddLVMpBf303RZrczJzHruM0RGgZpGv+AsoHIaV02wuaVSFHgftqIAIAiyjIi/NEz8jtgYooWJSS6Tfu++tA2omZ3pbe8ANiPTR+5TkkockRG8Sa2vrZnOXfxZpMFpE0oj2NdugPg8s4VF63yaXZ/Ik="
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
