language : java

addons:
  sonarcloud:
    organization: "Asy"
    token:
      secure: "tVEfRN3/BM2T3tgTQ3e9tZTgD6aNttmE8Q0yuu9RwSWDsV7HnpBhASUFF1f/XofJiBFwUT/x0i2UHH1rc3zqkFiGG++YzsT4SsXZIPRo2Q4Pf7PYGfGJ8zx8RWZWrNvWkhFKwkn7bf81my85PQuZIxw1ylB0JGRHYYIbcxFLzyueGfGO5jL551xuidpS1WZnVwu6TnPHR5KloBqwmVCOHuAEFLwzkixi0qJLNGTx3t1qHzx1mPpZS7rDpPREfEY2m8VbZyBQUyiuV+PRbaG7NIfsol216hDezbVgy7z5hAGORqylv4/nKJQWo90RXHUqcekxgpxF+cM875S0KIVinVXfm3Bl/2DzlTGcpI4tWZ5lrvkRH1XM/bAzDi//9l8qMHTCwpDoJOOrH72OluZgfAsZD1XLj+UE1vcaVe5GBmW2wuveaZCD0T4mPJhe93r2wlpw+8h6TVxaSS1RdqCRdWVIl0JoL/9li3LJh+Jwi68Iml3d8DjvG9XLHoWLJ1HXh1ADH1VFIWVzK20D5rzci9SM8ky+ZCzRDxTn5Wh+fdvO0DGf6uTYRKEXwNPTLtZZ+zO7NHMgghh/lo6DX9Un30oz9K+pgEMzCJtG4OkUrIt2VxbE/Y0OSbXn+UpcvZ1ph6aeJNL0l6tfM5qIiYkpYpuhnfXqaFLORCyrTVjPavc="
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
