# version format
version: '{build}'

os: Windows Server 2012

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
  - master
  - production
  - develop

  # blacklist
  except:
  - experimental

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

# Disable deployment
deploy: off